openapi: 3.0.3
info:
  title: OpenAPI schema for Victoria Metrics template .
components:
  schemas:
    variables:
      type: object
      properties:
        helm_release_name:
          title: Helm Release Name
          type: string
          description: The name of the Helm release.
          default: victoria-metrics-single
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: victoria-system
          x-walrus-ui:
            group: Basic
            order: 2
        helm_chart_version:
          title: Helm Chart Version
          type: string
          description: The version of the ingress-nginx Helm chart.
          default: 0.9.22
          x-walrus-ui:
            group: Basic
            order: 3
        set_custom_values:
          title: Set Custom Values
          type: boolean
          description: Set custom values
          default: false
          x-walrus-ui:
            group: Basic
            order: 4
        values:
          title: Values
          type: object
          description: Chart values
          default: {}
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
            widget: YamlEditor
      x-walrus-ui:
        groupOrder:
        - Basic
