openapi: 3.0.3
info:
  title: OpenAPI schema for Ingress-NGINX template .
components:
  schemas:
    variables:
      type: object
      properties:
        release_name:
          title: Release Name
          type: string
          description: The name of the Helm release.
          default: ingress-nginx
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: kube-system
          x-walrus-ui:
            group: Basic
            order: 2
        chart_version:
          title: Chart Version
          type: string
          description: The version of the ingress-nginx Helm chart.
          default: 4.11.2
          x-walrus-ui:
            group: Basic
            order: 3
      x-walrus-ui:
        groupOrder:
        - Basic